### ISSUE TITLE
[NEW FEATURE] Publish as Docker image

### ISSUE THREAD

**Issue by dnaka91** [mrjackwills/oxker#10]
**Is your feature request related to a problem? Please describe.**

Would be great to have this tool published as a Docker image on the main Docker registry, and maybe ghcr.io and quay.io as well. This would allow running it anywhere where Docker is installed, without having to install any additional machinery.

**Describe the solution you'd like**

Having automated builds and publishing to popular Docker image registries.

**Describe alternatives you've considered**

None really 🤷 

**Additional context**

Currently using another popular Docker container dashboard called [`ctop`](https://github.com/bcicen/ctop), and find **oxker** much nicer actually. Just would love to have it available as image so I could run it as follows:

```sh
docker run --rm -it --volume /var/run/docker.sock:/var/run/docker.sock:ro ghcr.io/mrjackwills/oxker:latest
```

**Comment by mrjackwills** [comment]
This sounds interesting, I have set up a dockerhub account, but have never published to it before.

How would you envision the docker container being created? And how could I test that on my home computer.

Even though oxker is based around Docker environments, I am clearly lacking some knowledge regarding it all.

**Comment by dnaka91** [comment]
Thanks for looking into it so quickly 🚀 

Not sure how (yet), but seems `ctop` is able to not show anything when viewing its own logs through their UI. Probably they do some heuristic detection for this as well (like checking that the image has a specific name or the ENTRYPOINT is a specific value).

I'll let you know once I find out how ctop does it, so maybe we can copy the method for oxker.

**Comment by mrjackwills** [comment]
I can exclude the oxker container from being listed, didn't realise that `ctop` did that, and in oxker would be easy enough to do, by just ignoring any container that uses `./oxker` as a command.

Next up, need to read up on how to create a multi-arch docker build

**Comment by dnaka91** [comment]
Tried it out today and works like a charm! Thank you so much.

**Comment by mrjackwills** [comment]
Sounds good, have created a github action to build a multi arch build on each release, so should all be kept up to date without having to think about it now.

I'll close this issue once the next release comes out, and hopefully the Docker Hub image will be updated automatically.

**Comment by mrjackwills** [comment]
build for v0.1.5 correctly updated the dockerhub image, so closing now, thanks
