### ISSUE TITLE
[BUG] Malformed escape codes in docker logs causes panic

### ISSUE THREAD

**Issue by gandalf3** [mrjackwills/oxker#17]
**Describe the bug**
Malformed color codes in docker log output cause panic (regardless of -c)

**To Reproduce**
1. Use software in a docker container which spews out partial ANSI escape codes, for example `ESC[\n`
2. [Oxker panics here](https://github.com/mrjackwills/oxker/blob/main/src/ui/color_match.rs#L45) when trying to parse the log (inside `cansi::v3::categorise_text`)

Here is a minimal demo of such a panic:

```rust
use cansi::v3::categorise_text;

fn main() {
    let x = categorise_text("oops\x1b[\n");
    println!("{}", x[0].text);
}
```

**Expected behavior**
Oxker is robust to garbage in log output

**Desktop (please complete the following information):**
 - OS: Linux

I understand this may be considered an upstream issue of the `cansi` crate; I've opened an issue there as well: https://github.com/kurtlawrence/cansi/issues/7

**Comment by mrjackwills** [comment]
Thank you, I will try have a look into this, I wonder if there any any better crates than cansi? Although ideally it could(?) be fixed upstream. I didn't really give it that much attention when selecting to use it.

In the mean time, do you have any ideas about how it could one could resolve it, or atleast try to remove the panic?

**Comment by mrjackwills** [comment]
I've updated the dependencies, and will create a new release by the end of the week, but I was never able to get the panic to occur on my system, although I didn't test it as thoroughly as I could/should have.

Can I ask what OS and terminal you were using? I'm on WSL2 Ubuntu (in, and out of, a Debian dev container) on Windows 11, with both Windows Terminal and whatever vscode was using

**Comment by gandalf3** [comment]
I was using alacritty on archlinux. As far as I know the panic should be terminal agnostic though as it occurs before the invalid characters are written to stdout.

**Comment by gandalf3** [comment]
Off topic but I happened to run across this crate https://github.com/uttarayan21/ansi-to-tui. It turns out it _also_ has bugs with invalid escape sequences and I don't think its handling overriding styles quite right, but bugs aside I think it could save you from maintaining most of `color_match.rs`. If you're still interested after my terrible sales pitch :sweat_smile:

I'm using it in oxker locally already and could make a PR for that as well as PRs to ansi-to-tui for the aforementioned issues. Fully understand if you'd rather just use cansi of course!

**Comment by mrjackwills** [comment]
Thanks, I'll have a look into that crate.

I think that the [tui-rs](https://github.com/fdehau/tui-rs) library is looking for maintainers, and/or contributors, so maybe it's something that one could attempt to add into it, so that it can handle ansi text natively? I don't know the internals of tui-rs enough to attempt it myself, yet
