### ISSUE TITLE
[NEW FEATURE] List Port

### ISSUE THREAD

**Issue by mrjackwills** [mrjackwills/oxker#21]
**Describe the solution you'd like**
Add a column for exposed port(s) for each container - a single container could expose many ports, so need to think the best way to display this, and also if any all interfaces, or 127.0.0.1 etc, and local to host mappings

**Additional context**
Maybe, in a not to distant future, enable the user to select which columns should be visible, would need to save this data somewhere

**Comment by kyoheiu** [comment]
This feature would be very appreciated if implemented. I run multiple containers in my VPS and am always confused which port is used.

**Comment by agarzon-orangerine** [comment]
Exactly one year later 😀, please add that feature.
