### ISSUE TITLE
[NEW FEATURE] Exec Shell - Open a container command line

### ISSUE THREAD

**Issue by varaskkar** [mrjackwills/oxker#28]
Hi, I discovered Oxker only a short time ago and I am delighted. I love how simple it is and its beautiful interface. So far I have been using ctop, it is not as nice but it has a feature that is a must for me which is "Exec Shell", that is, I can connect to the container through the console. The truth is that I would like to replace ctop by oxker for my daily use.

I would like to know if there are future plans to implement the connection to the container.

Screenshots:
https://i.imgur.com/7wIpc14.jpg
https://i.imgur.com/64L4EQw.jpg

**Comment by varaskkar** [comment]
Ohh sounds great, you made my day! Besides, I didn't know ratatui so that's cool

In fact yes, `ctop` cleans all the ui taking the whole screen. Not a bad option although I don't know if it would fit with oxker's design 🤔... 

`ctop` does one thing to display more information by pressing the left and right keys on a selected container. Left to show the log and Right to show cpu/ram/network,...it's as if it had 3 windows, the main one and 2 on the sides.

As an idea based on this, maybe a shell could be executed by pressing the right key or something similar.

But it occurs to me that if you press the right key while the container is selected, it may open a "new window" with the container shell without closing the "main window" and when you press the left key it returns to the main window.

Although another solution could be to press Enter when a container is selected, click on "exec shell" and split the log section in half... I'm not sure

**Comment by varaskkar** [comment]
Sure, and I was surprised how fast you released the new version 🎉 I'm gonna take a look at it.

> maybe keep a bar at the top, saying something like "You are currently in a shell of [container-name]"

I like this idea so much! (`ctop` doesn't do this).

**Comment by mrjackwills** [comment]
I have a basic working version, see the [feat/exec_tty](https://github.com/mrjackwills/oxker/tree/feat/exec_tty) branch, and specifically the [exec.rs](https://github.com/mrjackwills/oxker/blob/feat/exec_tty/src/exec.rs) file, but I cannot get it to execute correctly.

Specifically, when exiting a container shell, a user needs to press an additional key press before `oxker` enters the correct state, but I am at a loss as to where this specific issue, possible a lock, comes from.

The [feat/exec_tty](https://github.com/mrjackwills/oxker/tree/feat/exec_tty) branch at the moment shows a popup, telling the user to `press 'c' twice`, to resolve this issue, but obviously this is not in anyway a good solution.

There are other issues, and edge cases with container shells, that need to be fixed but they are all straight forward to resolve compared to this current quandary.
