### ISSUE TITLE
[NEW FEATURE] about column layout

### ISSUE THREAD

**Issue by user9931** [mrjackwills/oxker#32]
container names are on the right side of the table, plus and trunkated even if there's some space so it not too easy to understand what  its a container name

![image](https://github.com/mrjackwills/oxker/assets/62539068/69267175-320c-4cea-a422-b22dc8434829)

(on the image above, first line is "bitwarden" and second is "cloudflared")

Maybe its some idea behind, but at least have an option to switch to more "regular" view with "names" as first column, aligned to left side and trunkated to... 15-20 characters will be very helpful

**Comment by mrjackwills** [comment]
Yeah I can see the issue, the images name can also get especially long (looking at you VS Code dev containers).

The logs section includes both the current log line that you have selected, and the currently selected container name, to help with this issue.

I think there is more information that should be displayed, there's an open issue for listing a containers open ports, so maybe need to look into making the view a little more compact or efficient.

**Comment by dlvhdr** [comment]
I think having the container name first will be more intuitive to me. Its the first thing my eyes scan

**Comment by mrjackwills** [comment]
Yeah that probably makes sense, what order do you think the columns should be?

`name, state, status, cpu, mem, id, image, rx, tx`

Also think the image name should be truncated to 32 chars, the same approach as with the container name.
<img width="1261" alt="Screenshot 2023-12-30 145425" src="https://github.com/mrjackwills/oxker/assets/32690432/6b7f9f16-06f7-40ec-bcde-94c1d5b4c14b">

**Comment by dlvhdr** [comment]
Yeah makes sense. Maybe more usage of nerd font icons can make even more terse. Or stuff like "45 minutes" -> "45m" etc.

**Comment by mrjackwills** [comment]
nerd font icons?

**Comment by dlvhdr** [comment]
https://www.nerdfonts.com/

Some terminals support them out of the box, some require users to patch their font to add these extra symbols to it.

**Comment by mrjackwills** [comment]
This layout seem reasonable?

Also, an ellipsis added to the image/container name if it has 30 or more characters?
<img width="1214" alt="Screenshot 2024-01-01 163536" src="https://github.com/mrjackwills/oxker/assets/32690432/0d490f16-ac67-4a19-8f00-b4648eacf457">

**Comment by mrjackwills** [comment]
> a little off-topic: any hope for option (switch) to change text alignment to "more traditional" left?..

In terms of the headers and content?

Can be done with relative ease, could put it behind a `--left` flag, unless it looks substantially better than now on which case it would be default.

**Comment by mrjackwills** [comment]
> a little off-topic: any hope for option (switch) to change text alignment to "more traditional" left?..

Can you open this as a new issue?
