### ISSUE TITLE
[BUG] - Memory displayed incorrect

### ISSUE THREAD

**Issue by tanrak** [mrjackwills/oxker#33]
**Describe the bug**
Hi, the memory stats does not match with the original `docker stats`. Dozzle for example shows the correct stats but ctop (which seems abandoned) has a similar [problem](https://github.com/bcicen/ctop/issues/314) with the memory stats as oxker.

**To Reproduce**
1. start oxker
2. show memory stats
3. compare with `docker stats`

**Expected behavior**
The memory stats should be the same as `docker stats`.

**Desktop (please complete the following information):**
 - v0.6.0 - aarch64 - Raspberry Pi OS

**Comment by mrjackwills** [comment]
Thanks, I'll have a look at it.

I think `docker stats` reports in mebibytes and I think oxker uses Megabytes, maybe that is also causing some issue?

**Comment by tanrak** [comment]
> I think `docker stats` reports in mebibytes and `oxker` hopefully correctly converts to Megabytes, maybe that is also causing some issue?

I don't know. But for example my Syncthing-Container shows 37.46MiB per `docker stats` and oxker shows 43.67. If that were a problem with the conversion, the result would have to be 39.28?!

**Comment by mrjackwills** [comment]
Yeah sounds like it needs fixing, will have a look at it shortly
