### ISSUE TITLE
[BUG]  issue freeze when click on CPU to show from high to low

### ISSUE THREAD

**Issue by killmasta93** [mrjackwills/oxker#34]
Hi 
Currently when i run 
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock:ro --pull=always mrjackwills/oxker

and i click on the CPU from high to low it freezes up 

Thank you

![image](https://github.com/mrjackwills/oxker/assets/13953629/6d6333ef-dc95-49bb-911c-9b0747659a12)

**Comment by mrjackwills** [comment]
Is it possible to provide any further details, what kind of machine and operating system are you using?

I have tested on x86, armv6, and aarm64 machines, and I can't replicate the error

**Comment by killmasta93** [comment]
thanks for the reply, currently using ubuntu 20.04 LTS i realized it happens when i have lots of containers currently i have 120, if i try it on less it works fine

**Comment by mrjackwills** [comment]
I've not tested with 120 containers, can I ask you to run it with a ten second (10,000ms) update interval `oxker -d 10000` and see if that works. If not, try increasing the interval.

I have an idea for a fix, would you be able to test it if I created a branch/binary and shared the link with you?

**Comment by killmasta93** [comment]
hi there, i ran 

` docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock:ro --pull=always mrjackwills/oxker -d 10000`

same issue :(

sure you can create the link i can try it out :)

**Comment by mrjackwills** [comment]
Thanks, I spun up over 300 containers on my machine, and I couldn't get the crash to occur, so it's going to be hard for me to debug this issue.

Also, my idea for a fix is a lot more convoluted than I had originally expected, so it might be a while before I can get a new working binary for you to test.

**Comment by killmasta93** [comment]
hi there, so i think i figured out, what i did when i ran the container, i filter first on the RAM then i filter on the CPU and got it working, if anything ill post back again
