### ISSUE TITLE
[NEW FEATURE] Add filtering feature 

### ISSUE THREAD

**Issue by hgoumner** [mrjackwills/oxker#37]
Hello,

First I'd like to thank you for creating this great software. I use it daily.

Would it be possible to add a filtering feature (i.e. by container name, state, etc.)?

Thanks in advance.

**Comment by mrjackwills** [comment]
That's a good idea, maybe the user needs to press `F1` to enter, and exit, the filter mode. With a line to input text, possibly similar to how `htop` filtering works.

However, don't expect this any soon, by me at least, but I would like to implement it.
