### ISSUE TITLE
[NEW FEATURE] A failed healthcheck should make container not green

### ISSUE THREAD

**Issue by darkvertex** [mrjackwills/oxker#43]
**Is your feature request related to a problem? Please describe.**
The tool fools me into a sense of comfort until I read `(unhealthy)` and realize the green row is in fact in a bad state. Failing healthchecks should make rows red.

**Describe the solution you'd like**
I expect a failed healthcheck to color the container row red, or yellow, or some other color than "OK green".

**Comment by mrjackwills** [comment]
Yeah, you are correct, an unhealthy container shouldn't be green, was just about to release the next version, but this shouldn't be too much trouble to add in

**Comment by darkvertex** [comment]
Thanks man! 🚀
