### ISSUE TITLE
[NEW FEATURE] exec container option

### ISSUE THREAD

**Issue by iloveitaly** [mrjackwills/oxker#46]
**Is your feature request related to a problem? Please describe.**
I want to easily "jump into" a docker container.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add a "exec" to the right hand "option pane" and default the execution string to `bash -l`:

<img width="147" alt="image" src="https://github.com/user-attachments/assets/5e466654-a25a-45ad-8deb-fb74629f3b0d">

**Describe alternatives you've considered**
Manually executing the exec is fine, but defeats the purpose.

**Additional context**
Happy to submit a PR here—just point me in the right direction in the code to get started.

**Comment by mrjackwills** [comment]
Sorry if I am missing the point, but an input of the `e` keyboard button will exec into which ever container is currently selected.

I think the side controls should probably be kept solely for commands that change the state of the selected container.

**Comment by iloveitaly** [comment]
Ah, yes I was referring to the side controls. didn't realize `e` was an option.

Closing this out.
