### ISSUE TITLE
[NEW FEATURE] include stderr in logs

### ISSUE THREAD

**Issue by iloveitaly** [mrjackwills/oxker#48]
**Is your feature request related to a problem? Please describe.**
If the container is failing you can't see it from the log view.

**Describe the solution you'd like**
Include stderr in the log view.

**Describe alternatives you've considered**
Quit oxker, grab container sha, then use `docker logs SHA`

**Additional context**

**Comment by vincentmasse** [comment]
You can print to stderr with this python script and docker file.

```
FROM python:latest

COPY print_err.py root/app.py

CMD ["python", "root/app.py"]
```

```python
import sys


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


if __name__ == "__main__":
    print("This print to stdout")
    eprint("This should print to stderr")

```

**Comment by iloveitaly** [comment]
This is done! Thank you!
